hello
This is a log message
2023-04-28 17:27:32,480 INFO This is a log message
2023-04-28 17:27:32,480 ERROR An error occurred:
Traceback (most recent call last):
  File "C:\Users\PaulZhong\PycharmProjects\cde_timesheet\test.py", line 21, in <module>
    x = 1 / 0
ZeroDivisionError: division by zero
hello
2023-04-28 17:28:13,620 ERROR An error occurred:
Traceback (most recent call last):
  File "C:\Users\PaulZhong\PycharmProjects\cde_timesheet\test.py", line 20, in <module>
    x = 1 / 0
ZeroDivisionError: division by zero
